export  const languageData = {
    en: {
        home: "Home",
        about: "About Us",
        services: "Services",
        contact: "Contact Us",
        studyAbroad: "Study Abroad",
        more: "More",
        aboutKBM: "About KBM",
        learnAbout: "Learn about our mission, vision, and the team that makes it all happen.",
        learnMore: 'Learn More',
        company: 'Company',
        ourTeam: 'Our Team',
        missionVision: 'Mission & Team',
        whyChooseUs: 'Why Choose Us',
        successStories: 'Success Stories',
        testimonials: 'Testimonials',
        ourServices: 'Our Services',
        comprehensiveSolutions:'Comprehensive solutions to help you achieve your academic and career goals abroad.',
        viewServices: 'View All Services',
        counseling: 'Counseling',
        careerCounseling: 'Career Counseling',
        universitySelection: 'University Selection',
        visaAssistance: 'Visa Assistance',
        documentationHelp: 'Documentation Help',
        startFuture: 'Start Your Future Abroad',
        exploreStudy: 'Explore study opportunities in top destinations worldwide with expert guidance.',
        studyIn: 'Study In',
        viewOverview: 'View Overview',
        studyInJapan: 'Study In Japan',
        studyinAustralia: 'Study in Australia',
        studyinUnitedKingdom: 'Study in United Kingdom',
        studyinUSA: 'Study in USA',
        studyinCanada: 'Study in Canada',
        exploreMore: 'Explore More',
        discoveradditionalresources:'Discover additional resources, support, and information to help you succeed.',
        resources: 'Resources',
        gallery: 'Gallery',
        FAQ: 'FAQ',
        support: 'Support',
        contactSupport: 'Contact Support',
        yourGlobalPathway: 'Your Global Pathway',
        educationCareer: 'to Education & Career',
        homeHeroDesc: " We help students and professionals achieve their dreams abroad whether it's Japan, USA, Australia, UK, Canada, or other countries. From visas and documentation to pre-departure guidance and cultural adaptation, we support you at every step of your international journey."
    },
    jp: {
        home: "ホーム",
        about: "私たちについて",
        services: "サービス",
        contact: "お問い合わせ",
        studyAbroad: "留学",
        more: "もっと",
        aboutKBM: "KBMについて",
        learnAbout: "私たちのミッション、ビジョン、そしてそれを実現するチームについて学びましょう。",
        learnMore: '詳しく見る',
        company: '会社',
        ourTeam: '私たちのチーム',
        missionVision: '使命とビジョン',
        whyChooseUs: '私たちを選ぶ理由',
        successStories: '成功事例',
        testimonials: 'お客様の声',
        ourServices: '私たちのサービス',
        comprehensiveSolutions: '海外での学業とキャリアの目標達成を支援する包括的なソリューション。',
        viewServices: 'すべてのサービスを見る',
        counseling: 'カウンセリング',
        careerCounseling: 'キャリアカウンセリング',
        universitySelection: '大学選択',
        visaAssistance: 'ビザサポート',
        documentationHelp: '書類作成サポート',
        startFuture: '海外であなたの未来を始めましょう',
        exploreStudy: '専門家のガイダンスで、世界の主要な留学先での学びの機会を探りましょう。',
        studyIn: '留学先',
        viewOverview: '概要を見る',
        studyInJapan: '日本留学',
        studyinAustralia: 'オーストラリア留学',
        studyinUnitedKingdom:'イギリス留学',
        studyinUSA: 'アメリカ留学',
        studyinCanada: 'カナダ留学',
        exploreMore: 'さらに詳しく見る',
        discoveradditionalresources: '成功をサポートする追加のリソース、支援、情報を見つけましょう。',
        resources: 'リソース',
        gallery: 'ギャラリー',
        FAQ: 'よくある質問',
        support: 'サポート',
        contactSupport: 'サポートに連絡',
        yourGlobalPathway: 'あなたのグローバルへの道',
        educationCareer: '教育とキャリアへ',
        homeHeroDesc:'私たちは、学生や社会人が海外での夢を実現できるよう支援しています。日本、アメリカ、オーストラリア、イギリス、カナダ、その他の国々など、どこであっても対応します。ビザや書類手続きから出発前のガイダンス、文化への適応まで、国際的な旅のあらゆる段階であなたをサポートします。'
    },
}